const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const signal = () => ({connect() {}});
const make = (caption, resourceClass, output='DP-1') => ({caption,resourceClass,resourceName:'',output:{name:output},outputChanged:signal(),captionChanged:signal(),minimizedChanged:signal()});
const browser = make('aion2 global how to see animation canceling - Google Chrome','google-chrome','DP-2');
const game = make('AION2','steam_app_12345','DP-1');
let windows = [browser,game], output;
const context = vm.createContext({workspace:{windowList:()=>windows,windowAdded:signal(),windowRemoved:signal(),windowActivated:signal()},callDBus(...args) {output=args[4];}});
vm.runInContext(fs.readFileSync('ui/game-screen.js','utf8'),context);
assert.equal(output,'DP-1');
assert.equal(context.isGame(browser),false);
assert.equal(context.isGame(make('Search results for aion2.exe','org.kde.konsole')),false);
assert.equal(context.isGame(make('Game','aion2.exe')),true);
assert.equal(context.isGame(make('AION 2 (Global)','wine')),true);
assert.equal(context.isGame(make('AION2','google-chrome')),false);
windows = [browser];context.report();assert.equal(output,'');
windows = [game];game.output.name='HDMI-A-1';context.report();assert.equal(output,'HDMI-A-1');
console.log('Game matching, browser exclusion and display-change checks passed.');
